spring:
  rabbitmq:
    port: 5672
    host: "localhost"

  liquibase:
    enabled: ${LIQUIBASE_ENABLE:false}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none
    sql:
      init:
        mode: always

  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:root}

  application:
    name: person-service

  zipkin:
    enabled: ${ZIPKIN_MODE:false}

  main:
    banner-mode: off

logging:
  file:
    name: person-service.log
  level:
    org.springframework.jdbc.core: TRACE

management:
  endpoint:
    loggers:
      enabled: true

  endpoints:
    web:
      exposure:
        exclude: "health, info, loggers"

rabbit:
  queue:
    daily-queue: "daily_queue"
    alert-queue: "alert_queue"
    error-queue: "error_queue"