spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  liquibase:
    enabled: ${LIQUIBASE_ENABLE:false}
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:root}

  application:
    name: person-service

  zipkin:
    enabled: ${ZIPKIN_MODE:false}

  main:
    banner-mode: off

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  file:
    name: person-service.log
  level:
    org.springframework.jdbc.core: TRACE

management:
  endpoint:
    loggers:
      enabled: true

  endpoints:
    web:
      exposure:
        exclude: "health, info, loggers"