spring:
  liquibase:
    enabled: ${LIQUIBASE_ENABLE:false}
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=medical
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=medical
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:root}

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

